### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by hejingcao** [jlab-nlp/amr-nmt#1]

**Comment by vhientran** [comment]
Hi @arianakc 
Hopefully you can release the source code of your great work soon. Many thanks!

**Comment by arianakc** [comment]
> Hi @arianakc Hopefully you can release the source code of your great work soon. Many thanks!

Thanks for your attention to our work. I have been really busy, and I always was planning to upload the code but there is always something to make me busy, I currently just uploaded the code, but there are many dependent data files such as AMR parsed data I need to upload, and write the readme instructions, I'll do it soon.

**Comment by arianakc** [comment]
Instructions added.
